version: '2'

services:
  terraform:
    image: hashicorp/terraform
    working_dir: /app
    volumes:
      -  ./terra:/app
    environment:
      - TF_VAR_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - TF_VAR_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
