version: '2'

services:
  terraform:
    image: hashicorp/terraform
    working_dir: /app
    volumes:
      -  ./terra:/app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=us-east-1
      - GITHUB_TOKEN
      - GITHUB_ORGANIZATION=Test4d3d3d3
